/**
 * Represents car details with make, model, and common pros and cons.
 */
export interface CarDetails {
  /**
   * The make of the car (e.g., Toyota, Honda).
   */
  make: string;
  /**
   * The model of the car (e.g., Camry, Civic).
   */
  model: string;
    /**
   * An array of strings representing the available trims for the car model.
   */
  trims: string[];
  /**
   * The average price of the car model.
   */
  averagePrice: number;
  /**
   * An array of strings representing the pros of the car model.
   */
  pros: string[];
  /**
   * An array of strings representing the cons of the car model.
   */
  cons: string[];
   /**
   * A string representing if the model has hybrid or electric versions.
   */
  hybridOrElectric: string;
   /**
    * The type of car, such as SUV, Truck, Sedan, etc.
    */
   type: string;
   /**
    * The size of the car, such as compact, mid-size, or full-size.
    */
   size?: string;
}

/**
 * Categorizes cars based on their average price.
 * @param averagePrice The average price of the car.
 * @returns A string representing the price category of the car.
 */
function getPriceCategory(averagePrice: number): string {
  if (averagePrice < 25000) {
    return 'cheap';
  } else if (averagePrice >= 25000 && averagePrice < 45000) {
    return 'average';
  } else if (averagePrice >= 45000 && averagePrice < 100000) {
    return 'expensive';
  } else {
    return 'extremely expensive';
  }
}

/**
 * Asynchronously retrieves car details based on user-provided keywords.
 *
 * @param keywords An array of keywords provided by the user (e.g., SUV, EV, hatchback).
 * @returns A promise that resolves to an array of CarDetails objects matching the keywords.
 */
export async function getCarDetails(keywords: string[]): Promise<CarDetails[]> {
  const allCars: CarDetails[] = [
    {
      make: 'Toyota',
      model: 'RAV4',
      trims: ['LE', 'XLE', 'Limited'],
      averagePrice: 28000,
      pros: ['Reliable', 'Good resale value', 'Spacious interior', 'Great fuel economy'],
      cons: ['Basic features', 'Not very sporty', 'Mediocre fuel economy', 'Less cargo space than competitors'],
      hybridOrElectric: 'Hybrid Electric None',
      type: 'Crossover',
      size: 'compact',
    },
    {
      make: 'Ford',
      model: 'F-150',
      trims: ['XL', 'XLT', 'Lariat'],
      averagePrice: 35000,
      pros: ['Powerful', 'High towing capacity', 'Versatile', 'Wide range of configurations', 'Available with advanced tech'],
      cons: ['Poor fuel economy', 'Can be expensive', 'Large size', 'Base models lack features'],
      hybridOrElectric: 'Hybrid Electric None',
      type: 'Truck',
      size: 'full-size',
    },
    {
      make: 'Tesla',
      model: 'Model 3',
      trims: ['Standard Range Plus', 'Long Range', 'Performance'],
      averagePrice: 45000,
      pros: ['Electric', 'Advanced technology', 'Quick acceleration', 'Sleek design', 'Low running costs'],
      cons: ['Expensive', 'Charging infrastructure', 'Limited service centers', 'Range anxiety'],
      hybridOrElectric: 'Electric',
      type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Honda',
      model: 'Civic',
      trims: ['LX', 'Sport', 'EX'],
      averagePrice: 23000,
      pros: ['Fuel efficient', 'Fun to drive', 'Affordable', 'Reliable', 'Good safety ratings'],
      cons: ['Small back seat', 'Road noise', 'Basic interior', 'Less cargo space'],
      hybridOrElectric: 'None',
      type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Chevrolet',
      model: 'Suburban',
      trims: ['LS', 'LT', 'Premier'],
      averagePrice: 60000,
      pros: ['Very spacious', 'Powerful engine', 'Comfortable ride', 'Excellent for large families', 'High towing capacity'],
      cons: ['Expensive', 'Poor fuel economy', 'Hard to park', 'Bulky size'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'full-size',
    },
    {
      make: 'GMC',
      model: 'Sierra',
      trims: ['Base', 'SLE', 'SLT'],
      averagePrice: 40000,
      pros: ['Strong engine options', 'Comfortable interior', 'Good towing', 'Refined interior', 'Available with advanced features'],
      cons: ['Can be pricey', 'Lower fuel economy', 'Styling is subjective', 'Ride can be stiff'],
      hybridOrElectric: 'None',
      type: 'Truck',
      size: 'full-size',
    },
    {
      make: 'Chrysler',
      model: 'Pacifica',
      trims: ['Touring', 'Touring L', 'Limited'],
      averagePrice: 38000,
      pros: ['Spacious interior', 'Comfortable seating', 'Available hybrid option', 'Lots of storage', 'Smooth ride'],
      cons: ['Can be expensive', 'Styling is not for everyone', 'Some reliability concerns', 'Not very sporty'],
      hybridOrElectric: 'Hybrid',
      type: 'Minivan',
      size: 'full-size',
    },
    {
      make: 'Mazda',
      model: 'MX-5 Miata',
      trims: ['Sport', 'Club', 'Grand Touring'],
      averagePrice: 30000,
      pros: ['Fun to drive', 'Agile handling', 'Convertible', 'Affordable sports car', 'Stylish'],
      cons: ['Small interior', 'Limited cargo space', 'Not practical for families', 'Can be noisy'],
      hybridOrElectric: 'None',
      type: 'Sports Car',
      size: 'compact',
    },
    {
      make: 'Nissan',
      model: 'Rogue',
      trims: ['S', 'SV', 'SL'],
      averagePrice: 27000,
      pros: ['Comfortable ride', 'Spacious interior', 'Good fuel economy', 'User-friendly tech', 'Standard safety features'],
      cons: ['Mediocre acceleration', 'Engine noise', 'Not very sporty', 'Basic interior materials'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Jeep',
      model: 'Grand Cherokee',
      trims: ['Laredo', 'Limited', 'Overland'],
      averagePrice: 42000,
      pros: ['Off-road capability', 'Luxurious interior', 'Powerful engine options', 'Comfortable ride', 'Advanced tech'],
      cons: ['Poor fuel economy', 'Can be expensive', 'Reliability concerns', 'Large size'],
      hybridOrElectric: 'Hybrid Electric None',
      type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Ram',
      model: '1500',
      trims: ['Tradesman', 'Big Horn', 'Laramie'],
      averagePrice: 37000,
      pros: ['Comfortable ride', 'Luxurious interior', 'Powerful engine options', 'User-friendly tech', 'Good towing capacity'],
      cons: ['Poor fuel economy', 'Can be expensive', 'Large size', 'Reliability concerns'],
      hybridOrElectric: 'Hybrid Electric None',
      type: 'Truck',
      size: 'full-size',
    },
    {
      make: 'Hyundai',
      model: 'Tucson',
      trims: ['SE', 'SEL', 'Limited'],
      averagePrice: 26000,
      pros: ['Stylish design', 'Spacious interior', 'Good fuel economy', 'User-friendly tech', 'Long warranty'],
      cons: ['Mediocre acceleration', 'Engine noise', 'Not very sporty', 'Basic interior materials'],
      hybridOrElectric: 'Hybrid Electric None',
      type: 'SUV',
      size: 'compact',
    },
     {
      make: 'Toyota',
      model: 'Camry',
      trims: ['LE', 'XLE', 'SE', 'XSE', 'TRD'],
      averagePrice: 25295,
      pros: ['Reliable and durable', 'Fuel-efficient engine options', 'Comfortable ride'],
      cons: ['Bland styling', 'Not very sporty handling'],
      hybridOrElectric: 'Hybrid',
      type: 'Sedan',
      size: 'mid-size',
    },
    {
      make: 'Honda',
      model: 'CR-V',
      trims: ['LX', 'EX', 'EX-L', 'Touring'],
      averagePrice: 26800,
      pros: ['Spacious interior', 'Fuel-efficient', 'Reliable'],
      cons: ['Infotainment system can be frustrating to use'],
      hybridOrElectric: 'Hybrid',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Ford',
      model: 'Escape',
      trims: ['S', 'SE', 'SEL', 'Titanium'],
      averagePrice: 26010,
      pros: ['Multiple engine choices including hybrid', 'Agile handling'],
      cons: ['Less cargo space than competitors'],
      hybridOrElectric: 'Hybrid Electric None',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Chevrolet',
      model: 'Equinox',
      trims: ['L', 'LS', 'LT', 'Premier'],
      averagePrice: 23800,
      pros: ['Comfortable ride', 'User-friendly infotainment'],
      cons: ['Underpowered engine'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Hyundai',
      model: 'Elantra',
      trims: ['SE', 'SEL', 'Limited', 'N Line'],
      averagePrice: 20650,
      pros: ['Stylish design', 'Good fuel economy', 'Lots of standard features'],
      cons: ['Road noise can be intrusive'],
      hybridOrElectric: 'Hybrid',
      type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Nissan',
      model: 'Sentra',
      trims: ['S', 'SV', 'SR'],
      averagePrice: 19410,
      pros: ['Comfortable seats', 'Smooth ride'],
      cons: ['Slow acceleration'],
      hybridOrElectric: 'None',
      type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Mazda',
      model: 'CX-5',
      trims: ['Sport', 'Touring', 'Grand Touring', 'Signature'],
      averagePrice: 25370,
      pros: ['Fun to drive', 'Upscale interior'],
      cons: ['Less cargo space than rivals'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Subaru',
      model: 'Forester',
      trims: ['Base', 'Premium', 'Sport', 'Limited', 'Touring'],
      averagePrice: 24795,
      pros: ['Standard all-wheel drive', 'Spacious interior', 'Good visibility'],
      cons: ['Slow acceleration'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Kia',
      model: 'Sportage',
      trims: ['LX', 'EX', 'SX', 'Prestige'],
      averagePrice: 23990,
      pros: ['Stylish design', 'Long warranty'],
      cons: ['Firm ride'],
      hybridOrElectric: 'Hybrid Electric',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Volkswagen',
      model: 'Tiguan',
      trims: ['S', 'SE', 'SEL', 'SEL Premium R-Line'],
      averagePrice: 24945,
      pros: ['Spacious third-row seating option', 'Comfortable ride'],
      cons: ['Sluggish acceleration'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'GMC',
      model: 'Terrain',
      trims: ['SLE', 'SLT', 'AT4', 'Denali'],
      averagePrice: 25995,
      pros: ['User-friendly infotainment system'],
      cons: ['Underpowered engine'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Toyota',
      model: 'Tacoma',
      trims: ['SR', 'SR5', 'TRD Sport', 'TRD Off-Road', 'Limited', 'TRD Pro'],
      averagePrice: 26400,
      pros: ['Off-road capability', 'Strong resale value'],
      cons: ['Small rear seats', 'Stiff ride'],
      hybridOrElectric: 'None',
      type: 'Truck',
      size: 'mid-size',
    },
    {
      make: 'Chevrolet',
      model: 'Colorado',
      trims: ['Base', 'Work Truck', 'LT', 'Z71', 'ZR2'],
      averagePrice: 25200,
      pros: ['Multiple engine options', 'Off-road capability (ZR2)'],
      cons: ['Small rear seats', 'Basic interior'],
      hybridOrElectric: 'None',
      type: 'Truck',
      size: 'mid-size',
    },
    {
      make: 'Jeep',
      model: 'Wrangler',
      trims: ['Sport', 'Sport S', 'Sahara', 'Rubicon'],
      averagePrice: 29070,
      pros: ['Off-road capability', 'Convertible top options'],
      cons: ['Uncomfortable on-road ride', 'Noisy'],
      hybridOrElectric: 'Hybrid Electric None',
      type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Subaru',
      model: 'Outback',
      trims: ['Base', 'Premium', 'Limited', 'Touring', 'Onyx Edition XT', 'Wilderness'],
      averagePrice: 26945,
      pros: ['Standard all-wheel drive', 'Spacious interior', 'Good safety ratings'],
      cons: ['Underpowered base engine'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'mid-size',
    },
     {
      make: 'Kia',
      model: 'Telluride',
      trims: ['LX', 'EX', 'SX', 'SX Prestige'],
      averagePrice: 32190,
      pros: ['Spacious interior', 'Stylish design', 'Lots of features for the price'],
      cons: ['Can be hard to find at dealerships'],
      hybridOrElectric: 'None',
      type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Hyundai',
      model: 'Palisade',
      trims: ['SE', 'SEL', 'Limited', 'Calligraphy'],
      averagePrice: 32525,
      pros: ['Comfortable ride', 'Spacious interior', 'User-friendly tech'],
      cons: ['Mediocre fuel economy'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Honda',
      model: 'Pilot',
      trims: ['LX', 'EX', 'EX-L', 'Touring', 'Elite'],
      averagePrice: 32250,
      pros: ['Spacious third-row seating', 'Reliable', 'Smooth ride'],
      cons: ['Bland styling'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Dodge',
      model: 'Durango',
      trims: ['SXT', 'GT', 'R/T', 'Citadel', 'SRT'],
      averagePrice: 30795,
      pros: ['Powerful engine options', 'Available third-row seating', 'Aggressive styling'],
      cons: ['Poor fuel economy'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Ford',
      model: 'Explorer',
      trims: ['Base', 'XLT', 'Limited', 'ST', 'Platinum'],
      averagePrice: 32775,
      pros: ['Available hybrid model', 'Sporty ST trim'],
      cons: ['Tight third-row seating'],
      hybridOrElectric: 'Hybrid None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Toyota',
      model: '4Runner',
      trims: ['SR5', 'TRD Off-Road', 'Limited', 'TRD Pro'],
      averagePrice: 36765,
      pros: ['Off-road capability', 'Reliable'],
      cons: ['Outdated design', 'Poor fuel economy'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'BMW',
      model: 'X5',
      trims: ['sDrive40i', 'xDrive40i', 'xDrive45e', 'M50i'],
      averagePrice: 59400,
      pros: ['Luxurious interior', 'Powerful engine options', 'Refined driving dynamics'],
      cons: ['Expensive', 'Options can add up quickly'],
      hybridOrElectric: 'Hybrid None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Mercedes-Benz',
      model: 'GLE',
      trims: ['GLE 350', 'GLE 450', 'GLE 580', 'AMG GLE 53', 'AMG GLE 63 S'],
      averagePrice: 54750,
      pros: ['Luxurious interior', 'Advanced technology', 'Comfortable ride'],
      cons: ['Expensive', 'Complex infotainment system'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Audi',
      model: 'Q7',
      trims: ['45 TFSI Premium', '45 TFSI Premium Plus', '55 TFSI Premium Plus', '55 TFSI Prestige'],
      averagePrice: 54950,
      pros: ['Refined interior', 'Comfortable ride', 'User-friendly tech'],
      cons: ['Less sporty than rivals'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Lexus',
      model: 'RX',
      trims: ['RX 350', 'RX 350 F Sport', 'RX 450h', 'RX 450h F Sport'],
      averagePrice: 45170,
      pros: ['Luxurious interior', 'Reliable', 'Smooth ride'],
      cons: ['Uninspired handling'],
      hybridOrElectric: 'Hybrid None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Acura',
      model: 'MDX',
      trims: ['Base', 'Technology', 'A-Spec', 'Advance'],
      averagePrice: 44500,
      pros: ['Spacious interior', 'Lots of features for the price', 'Sporty handling (A-Spec)'],
      cons: ['Infotainment system can be confusing'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Infiniti',
      model: 'QX60',
      trims: ['Pure', 'Luxe', 'Sensory'],
      averagePrice: 44350,
      pros: ['Comfortable ride', 'Luxurious interior'],
      cons: ['Less sporty than rivals'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Cadillac',
      model: 'XT5',
      trims: ['Luxury', 'Premium Luxury', 'Sport'],
      averagePrice: 44095,
      pros: ['Comfortable ride', 'Stylish interior'],
      cons: ['Underpowered engine'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Lincoln',
      model: 'Nautilus',
      trims: ['Standard', 'Reserve', 'Black Label'],
      averagePrice: 41940,
      pros: ['Luxurious interior', 'Comfortable ride', 'Quiet cabin'],
      cons: ['Less sporty than rivals'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Volvo',
      model: 'XC60',
      trims: ['Momentum', 'R-Design', 'Inscription'],
      averagePrice: 41700,
      pros: ['Stylish design', 'Comfortable seats', 'Lots of standard safety features'],
      cons: ['Infotainment system can be confusing'],
      hybridOrElectric: 'Hybrid',
       type: 'SUV',
      size: 'mid-size',
    },
    {
      make: 'Land Rover',
      model: 'Range Rover Evoque',
      trims: ['S', 'SE', 'R-Dynamic S', 'R-Dynamic SE'],
      averagePrice: 43750,
      pros: ['Stylish design', 'Off-road capability', 'Luxurious interior'],
      cons: ['Small cargo space', 'Expensive'],
      hybridOrElectric: 'Hybrid',
       type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Porsche',
      model: 'Macan',
      trims: ['Base', 'S', 'GTS', 'Turbo'],
      averagePrice: 54900,
      pros: ['Sporty handling', 'Powerful engine options', 'Luxurious interior'],
      cons: ['Expensive', 'Small cargo space'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Alfa Romeo',
      model: 'Stelvio',
      trims: ['Sprint', 'Ti', 'Veloce', 'Quadrifoglio'],
      averagePrice: 42950,
      pros: ['Sporty handling', 'Stylish design', 'Powerful engine options'],
      cons: ['Reliability concerns', 'Small cargo space'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Tesla',
      model: 'Model Y',
      trims: ['Long Range', 'Performance'],
      averagePrice: 53990,
      pros: ['Electric', 'Quick acceleration', 'Advanced technology', 'Spacious interior'],
      cons: ['Expensive', 'Charging infrastructure', 'Limited service centers'],
      hybridOrElectric: 'Electric',
       type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Ford',
      model: 'Bronco',
      trims: ['Base', 'Big Bend', 'Black Diamond', 'Outer Banks', 'Badlands', 'Wildtrak', 'Everglades'],
      averagePrice: 30800,
      pros: ['Off-road capability', 'Convertible top options', 'Retro styling'],
      cons: ['Noisy on-road ride', 'Poor fuel economy'],
      hybridOrElectric: 'None',
       type: 'SUV',
      size: 'compact',
    },
    {
      make: 'Mercedes-Benz',
      model: 'C-Class',
      trims: ['C 300', 'AMG C 43', 'AMG C 63'],
      averagePrice: 41600,
      pros: ['Luxurious interior', 'Comfortable ride', 'Advanced technology'],
      cons: ['Expensive', 'Complex infotainment system'],
      hybridOrElectric: 'None',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'BMW',
      model: '3 Series',
      trims: ['330i', '330e', 'M340i', 'M3'],
      averagePrice: 41450,
      pros: ['Sporty handling', 'Powerful engine options', 'Luxurious interior'],
      cons: ['Expensive', 'Options can add up quickly'],
      hybridOrElectric: 'Hybrid None',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Audi',
      model: 'A4',
      trims: ['40 TFSI Premium', '40 TFSI Premium Plus', '45 TFSI Premium Plus', '45 TFSI Prestige'],
      averagePrice: 39100,
      pros: ['Refined interior', 'Comfortable ride', 'User-friendly tech'],
      cons: ['Less sporty than rivals'],
      hybridOrElectric: 'None',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Lexus',
      model: 'ES',
      trims: ['ES 350', 'ES 350 F Sport', 'ES 300h'],
      averagePrice: 40000,
      pros: ['Luxurious interior', 'Reliable', 'Smooth ride'],
      cons: ['Uninspired handling'],
      hybridOrElectric: 'Hybrid None',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Acura',
      model: 'TLX',
      trims: ['Base', 'Technology', 'A-Spec', 'Advance', 'Type S'],
      averagePrice: 37500,
      pros: ['Sporty handling (Type S)', 'Lots of features for the price'],
      cons: ['Infotainment system can be confusing'],
      hybridOrElectric: 'None',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Infiniti',
      model: 'Q50',
      trims: ['Luxe', 'Sensory', 'Red Sport 400'],
      averagePrice: 36600,
      pros: ['Powerful engine options (Red Sport 400)', 'Comfortable seats'],
      cons: ['Outdated design', 'Less sporty than rivals'],
      hybridOrElectric: 'None',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Cadillac',
      model: 'CT5',
      trims: ['Luxury', 'Premium Luxury', 'Sport', 'V-Series'],
      averagePrice: 37295,
      pros: ['Stylish design', 'Comfortable ride', 'Sporty handling (V-Series)'],
      cons: ['Underpowered base engine'],
      hybridOrElectric: 'None',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Genesis',
      model: 'G70',
      trims: ['2.0T', '3.3T'],
      averagePrice: 36000,
      pros: ['Sporty handling', 'Luxurious interior', 'Lots of features for the price'],
      cons: ['Small rear seats'],
      hybridOrElectric: 'None',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Volvo',
      model: 'S60',
      trims: ['Momentum', 'R-Design', 'Inscription', 'Polestar Engineered'],
      averagePrice: 40300,
      pros: ['Stylish design', 'Comfortable seats', 'Lots of standard safety features', 'Sporty handling (Polestar Engineered)'],
      cons: ['Infotainment system can be confusing'],
      hybridOrElectric: 'Hybrid',
       type: 'Sedan',
      size: 'compact',
    },
    {
      make: 'Subaru',
      model: 'Impreza',
      trims: ['Base', 'Premium', 'Sport', 'Limited'],
      averagePrice: 18795,
      pros: ['Standard all-wheel drive', 'Good fuel economy'],
      cons: ['Slow acceleration', 'Basic interior'],
      hybridOrElectric: 'None',
       type: 'Sedan',
      size: 'compact',
    },
     {
        make: 'Volkswagen',
        model: 'Jetta',
        trims: ['S', 'SE', 'SEL', 'GLI'],
        averagePrice: 20195,
        pros: ['Fuel-efficient', 'Spacious interior'],
        cons: ['Basic interior materials', 'Not as engaging to drive'],
        hybridOrElectric: 'None',
        type: 'Sedan',
        size: 'compact',
      },
      {
        make: 'Kia',
        model: 'Forte',
        trims: ['FE', 'LXS', 'GT-Line', 'EX', 'GT'],
        averagePrice: 18855,
        pros: ['Affordable', 'Long warranty'],
        cons: ['Engine can be noisy', 'Ride can be firm'],
        hybridOrElectric: 'None',
        type: 'Sedan',
        size: 'compact',
      },
      {
        make: 'Hyundai',
        model: 'Sonata',
        trims: ['SE', 'SEL', 'SEL Plus', 'Limited', 'N Line'],
        averagePrice: 23950,
        pros: ['Stylish design', 'Comfortable ride'],
        cons: ['Controversial styling', 'Some controls can be confusing'],
        hybridOrElectric: 'Hybrid',
        type: 'Sedan',
        size: 'mid-size',
      },
       {
        make: 'Toyota',
        model: 'Highlander',
        trims: ['L', 'LE', 'XLE', 'Limited', 'Platinum'],
        averagePrice: 34810,
        pros: ['Reliable', 'Spacious interior', 'Available hybrid'],
        cons: ['Not particularly sporty', 'Infotainment could be better'],
        hybridOrElectric: 'Hybrid',
        type: 'SUV',
        size: 'mid-size',
      },
      {
        make: 'Ford',
        model: 'Expedition',
        trims: ['XL STX', 'XLT', 'Limited', 'King Ranch', 'Platinum'],
        averagePrice: 50595,
        pros: ['Spacious interior', 'Powerful engine', 'Good towing capacity'],
        cons: ['Large and hard to maneuver', 'Poor fuel economy'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'full-size',
      },
       {
        make: 'Chevrolet',
        model: 'Tahoe',
        trims: ['LS', 'LT', 'RST', 'Z71', 'Premier', 'High Country'],
        averagePrice: 49700,
        pros: ['Spacious interior', 'Comfortable ride'],
        cons: ['Large size', 'Can be expensive'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'full-size',
      },
      {
        make: 'GMC',
        model: 'Yukon',
        trims: ['SLE', 'SLT', 'AT4', 'Denali', 'Denali Ultimate'],
        averagePrice: 51600,
        pros: ['Upscale interior', 'Comfortable ride', 'Powerful engine'],
        cons: ['Expensive', 'Large size'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'full-size',
      },
      {
        make: 'Cadillac',
        model: 'Escalade',
        trims: ['Luxury', 'Premium Luxury', 'Sport', 'Platinum'],
        averagePrice: 76295,
        pros: ['Luxurious interior', 'Advanced technology', 'Comfortable ride'],
        cons: ['Very expensive', 'Large size'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'full-size',
      },
       {
        make: 'Lincoln',
        model: 'Navigator',
        trims: ['Premiere', 'Reserve', 'Black Label'],
        averagePrice: 76720,
        pros: ['Luxurious interior', 'Comfortable ride', 'Quiet cabin'],
        cons: ['Very expensive', 'Large size'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'full-size',
      },
      {
        make: 'Chrysler',
        model: '300',
        trims: ['Touring', 'Touring L', 'S'],
        averagePrice: 30945,
        pros: ['Comfortable ride', 'Spacious interior'],
        cons: ['Outdated design', 'Poor fuel economy'],
        hybridOrElectric: 'None',
        type: 'Sedan',
        size: 'full-size',
      },
      {
        make: 'Dodge',
        model: 'Charger',
        trims: ['SXT', 'GT', 'R/T', 'Scat Pack', 'Hellcat'],
        averagePrice: 30470,
        pros: ['Powerful engine options', 'Aggressive styling'],
        cons: ['Poor fuel economy', 'Outdated interior'],
        hybridOrElectric: 'None',
        type: 'Sedan',
        size: 'full-size',
      },
      {
        make: 'Nissan',
        model: 'Titan',
        trims: ['S', 'SV', 'Pro-4X', 'SL', 'Platinum Reserve'],
        averagePrice: 36550,
        pros: ['Comfortable ride', 'Standard safety features'],
        cons: ['Less capable than rivals', 'Outdated interior'],
        hybridOrElectric: 'None',
        type: 'Truck',
        size: 'full-size',
      },
        {
        make: 'Toyota',
        model: 'Tundra',
        trims: ['SR', 'SR5', 'Limited', 'Platinum', '1794 Edition', 'TRD Pro'],
        averagePrice: 36425,
        pros: ['Reliable', 'Spacious interior', 'Good resale value'],
        cons: ['Not as fuel-efficient as rivals', 'Can be expensive'],
        hybridOrElectric: 'Hybrid None',
        type: 'Truck',
        size: 'full-size',
      },
         {
        make: 'GMC',
        model: 'Canyon',
        trims: ['Elevation', 'AT4', 'Denali'],
        averagePrice: 36600,
        pros: ['Capable off-road', 'Comfortable ride'],
        cons: ['Less spacious than some rivals', 'Can be expensive'],
        hybridOrElectric: 'None',
        type: 'Truck',
        size: 'mid-size',
      },
      {
        make: 'Ford',
        model: 'Ranger',
        trims: ['XL', 'XLT', 'Lariat'],
        averagePrice: 25500,
        pros: ['Easy to maneuver', 'Good fuel economy'],
        cons: ['Basic interior', 'Not as capable as some rivals'],
        hybridOrElectric: 'None',
        type: 'Truck',
        size: 'mid-size',
      },
          {
        make: 'Honda',
        model: 'Accord',
        trims: ['LX', 'Sport', 'EX', 'EX-L', 'Touring'],
        averagePrice: 27290,
        pros: ['Spacious interior', 'Fuel-efficient', 'Reliable'],
        cons: ['Infotainment system can be frustrating to use', 'Bland styling'],
        hybridOrElectric: 'Hybrid',
        type: 'Sedan',
        size: 'mid-size',
      },
       {
        make: 'Hyundai',
        model: 'Kona',
        trims: ['SE', 'SEL', 'Limited', 'N Line', 'Ultimate'],
        averagePrice: 21990,
        pros: ['Stylish design', 'Good fuel economy', 'Available electric version'],
        cons: ['Small back seat', 'Road noise'],
        hybridOrElectric: 'Electric None',
        type: 'SUV',
        size: 'subcompact',
      },
       {
        make: 'Mazda',
        model: 'CX-30',
        trims: ['2.5 S', 'Select', 'Preferred', 'Carbon Edition', 'Premium', 'Turbo'],
        averagePrice: 22050,
        pros: ['Stylish design', 'Fun to drive'],
        cons: ['Small back seat', 'Limited cargo space'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'subcompact',
      },
       {
        make: 'Toyota',
        model: 'Corolla',
        trims: ['L', 'LE', 'XLE', 'SE', 'XSE'],
        averagePrice: 20025,
        pros: ['Reliable and durable', 'Fuel-efficient engine options', 'Comfortable ride'],
        cons: ['Bland styling', 'Not very sporty handling'],
        hybridOrElectric: 'Hybrid',
        type: 'Sedan',
        size: 'compact',
      },
           {
        make: 'Kia',
        model: 'Seltos',
        trims: ['LX', 'S', 'EX', 'SX'],
        averagePrice: 22470,
        pros: ['Stylish design', 'Good warranty', 'Available all-wheel drive'],
        cons: ['Engine can be noisy', 'Ride can be firm'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'subcompact',
      },
           {
        make: 'Honda',
        model: 'HR-V',
        trims: ['LX', 'Sport', 'EX-L'],
        averagePrice: 21420,
        pros: ['Spacious interior', 'Good fuel economy'],
        cons: ['Slow acceleration', 'Noisy engine'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'subcompact',
      },
      {
        make: 'Mitsubishi',
        model: 'Outlander',
        trims: ['ES', 'SE', 'SEL', 'GT'],
        averagePrice: 26995,
        pros: ['Available third-row seating', 'Long warranty'],
        cons: ['Not very sporty', 'Can be noisy'],
        hybridOrElectric: 'Hybrid Electric',
        type: 'SUV',
        size: 'compact',
      },
           {
        make: 'Buick',
        model: 'Encore',
        trims: ['Preferred'],
        averagePrice: 24600,
        pros: ['Easy to park', 'Quiet cabin'],
        cons: ['Small back seat', 'Not very sporty'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'subcompact',
      },
           {
        make: 'Chevrolet',
        model: 'Trax',
        trims: ['LS', 'LT'],
        averagePrice: 21400,
        pros: ['Affordable', 'Easy to park'],
        cons: ['Small back seat', 'Not very sporty'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'subcompact',
      },
                {
        make: 'Nissan',
        model: 'Kicks',
        trims: ['S', 'SV', 'SR'],
        averagePrice: 19500,
        pros: ['Affordable', 'Good fuel economy'],
        cons: ['Slow acceleration', 'Not very sporty'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'subcompact',
      },
               {
        make: 'Jeep',
        model: 'Compass',
        trims: ['Sport', 'Latitude', 'Limited', 'Trailhawk'],
        averagePrice: 25900,
        pros: ['Capable off-road', 'Stylish design'],
        cons: ['Slow acceleration', 'Not very fuel-efficient'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'compact',
      },
        {
        make: 'Volkswagen',
        model: 'Taos',
        trims: ['S', 'SE', 'SEL'],
        averagePrice: 22995,
        pros: ['Spacious interior', 'Good fuel economy'],
        cons: ['Slow acceleration', 'Not very sporty'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'subcompact',
      },
        {
        make: 'Hyundai',
        model: 'Venue',
        trims: ['SE', 'SEL', 'Limited'],
        averagePrice: 19000,
        pros: ['Affordable', 'Good fuel economy'],
        cons: ['Small back seat', 'Slow acceleration'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'subcompact',
      },
           {
        make: 'Mercedes-Benz',
        model: 'GLC',
        trims: ['GLC 300', 'AMG GLC 43', 'AMG GLC 63'],
        averagePrice: 43850,
        pros: ['Luxurious interior', 'Comfortable ride', 'Advanced technology'],
        cons: ['Expensive', 'Complex infotainment system'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'compact',
      },
           {
        make: 'BMW',
        model: 'X3',
        trims: ['xDrive30i', 'M40i', 'X3 M'],
        averagePrice: 43700,
        pros: ['Sporty handling', 'Powerful engine options', 'Luxurious interior'],
        cons: ['Expensive', 'Options can add up quickly'],
        hybridOrElectric: 'Hybrid None',
        type: 'SUV',
        size: 'compact',
      },
                  {
        make: 'Audi',
        model: 'Q5',
        trims: ['40 TFSI Premium', '40 TFSI Premium Plus', '45 TFSI Premium Plus', '45 TFSI Prestige'],
        averagePrice: 43300,
        pros: ['Refined interior', 'Comfortable ride', 'User-friendly tech'],
        cons: ['Less sporty than rivals'],
        hybridOrElectric: 'Hybrid',
        type: 'SUV',
        size: 'compact',
      },
                               {
        make: 'Cadillac',
        model: 'XT4',
        trims: ['Luxury', 'Premium Luxury', 'Sport'],
        averagePrice: 35700,
        pros: ['Stylish design', 'Comfortable ride', 'Lots of features for the price'],
        cons: ['Underpowered engine', 'Infotainment system can be confusing'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'compact',
      },
                                {
        make: 'Lexus',
        model: 'NX',
        trims: ['NX 250', 'NX 350', 'NX 350h', 'NX 450h+'],
        averagePrice: 37950,
        pros: ['Luxurious interior', 'Reliable', 'Smooth ride', 'Available hybrid and plug-in hybrid'],
        cons: ['Uninspired handling', 'Infotainment system can be frustrating to use'],
        hybridOrElectric: 'Hybrid Electric',
        type: 'SUV',
        size: 'compact',
      },
            {
        make: 'Acura',
        model: 'RDX',
        trims: ['Base', 'Technology', 'A-Spec', 'Advance'],
        averagePrice: 40600,
        pros: ['Spacious interior', 'Lots of features for the price', 'Sporty handling (A-Spec)'],
        cons: ['Infotainment system can be confusing', 'No hybrid option'],
        hybridOrElectric: 'None',
        type: 'SUV',
        size: 'compact',
      },
  ];

  // Convert keywords to lowercase for case-insensitive matching
  const lowerCaseKeywords = keywords.map(keyword => keyword.toLowerCase());

  // Filter car details based on keywords
  const filteredCars = allCars.filter(car => {
    // Check if any keyword matches the car's type, make, model, price category, or size
    const matchesKeywords = lowerCaseKeywords.some(keyword => {
      const carValues = [car.type, car.make, car.model, getPriceCategory(car.averagePrice), car.size || ''].map(value => value.toLowerCase());
      return carValues.some(carValue => carValue.includes(keyword));
    });

    const isElectricOrHybrid = lowerCaseKeywords.includes('electric') ? car.hybridOrElectric.includes('Electric') : lowerCaseKeywords.includes('hybrid') ? car.hybridOrElectric.includes('Hybrid') : true;


    return matchesKeywords && isElectricOrHybrid;
  });

  return filteredCars;
}
